### ISSUE TITLE
Adding a toPosix function

### ISSUE THREAD

**Issue by dawehner** [justinmimbs/elm-date-basic#1]
For compability with ```elm/time``` and probably a good amount of other libraries it would be quite nice to have conversion functions from and to posix, see https://alpha.elm-lang.org/packages/elm/time/1.0.0/Time#Posix

**Comment by justinmimbs** [comment]
Hi Daniel,

This `Date` is meant to represent a date abstractly; the period of time it covers depends on where you are on earth. The `Posix` in `elm/time` is meant to represent a time concretely; the instant in time it points to is the same everywhere on earth.

To convert `Date` from `Posix` we'd need an [offset](https://en.wikipedia.org/wiki/UTC_offset) to be able to interpret the given time as a date; and to convert `Date` to `Posix` we'd need an offset to be able to interpret the given date (presumably at midnight) as a time.

This package is useful for working with dates in a general sense, when bringing along times and offsets would be too specific.

I think functions that deal with times and offsets would fit better in a `Posix`-oriented package.

That said, do you have a specific use-case in mind?

Thanks,

Justin

**Comment by JDemler** [comment]
One use-case I can think of:

`Date.fromPosix` to be used in combination with `Time.now` to get the current (naive) date.

Or a `Date.today` function.

**Comment by justinmimbs** [comment]
This package could expose `Date.today` as a task, as it would have to rely on the `Time.now` and `Time.here` tasks. I like that idea.

I think a function for `Date.fromPosix` shouldn't elide the concept of time offsets, so it would have the signature `Time.Zone -> Posix -> Date`. This is what I tried to explain above. To give an example: if you and I each asked for `Time.now` at the same instant, we would both get the same value, even if we were in different parts of the world. But for you the date might be `2018-08-30`, and for me it might be `2018-08-29`. The `Posix` value alone says nothing about how to interpret that instant in human terms.

**Comment by JDemler** [comment]
Yes... after thinking about it again `Time.Zone -> Posix -> Date` seems to be the only sensible signature.

`Date.today` would be really awesome :+1:

**Comment by JDemler** [comment]
I've just written this stuff because I need it for the port of `elm-community/elm-datepicker`.

Currently I have no time to write a pr + docs so if you want to use these functions please help yourself :)
Otherwise I will send you a PR next week.


``` elm
today : Task Never Date
today =
    Time.now
        |> Task.andThen
            (\posix ->
                Time.here
                    |> Task.map
                        (\zone -> fromPosix zone posix)
            )


fromPosix : Time.Zone -> Time.Posix -> Date
fromPosix zone posix =
    Date.fromCalendarDate
        (Time.toYear zone posix)
        (Time.toMonth zone posix |> timeMonthToDateMonth)
        (Time.toDay zone posix)

timeMonthToDateMonth : Time.Month -> Month
timeMonthToDateMonth month =
    case month of
        Time.Jan -> Jan
        Time.Feb -> Feb
        Time.Mar -> Mar
        Time.Apr -> Apr
        Time.May -> May
        Time.Jun -> Jun
        Time.Jul -> Jul
        Time.Aug -> Aug
        Time.Sep -> Sep
        Time.Oct -> Oct
        Time.Nov -> Nov
        Time.Dec -> Dec
```

**Comment by justinmimbs** [comment]
Thanks, Jakob. I've added `Date.today` and published an update: https://package.elm-lang.org/packages/justinmimbs/date/1.1.0/Date#today

**Comment by justinmimbs** [comment]
I'm closing this for now. For getting the current date I've added `Date.today`, and for better compatibility with `elm/time` I've changed to using its `Month` and `Weekday` types. It's now straightforward to convert a `Posix` and a `Zone` to a `Date`, simplifying the above to this:

```elm
fromPosix : Time.Zone -> Time.Posix -> Date
fromPosix zone posix =
    Date.fromCalendarDate
        (Time.toYear zone posix)
        (Time.toMonth zone posix)
        (Time.toDay zone posix)
```

**Comment by dawehner** [comment]
Thank you!
