### ISSUE TITLE
Human-readable value display in elm-test diffs

### ISSUE THREAD

**Issue by j-maas** [justinmimbs/elm-date-basic#10]
I am not sure, how this can be done. A quick search didn't bring up any hints...

My issue is that when testing with dates and they don't match, the diff from `elm-test` looks like
```
    RD 736956
    ╷
    │ Expect.equal
    ╵
    RD 736969
```

It would be much more helpful, if it would display in ISO format instead:
```
    Date 2018-10-06
    ╷
    │ Expect.equal
    ╵
    Date 2018-11-06
```

Again, I'm not sure how easily this is possible. If you can point me to resources on how this might be done, I could take a crack at creating a PR.

**Comment by justinmimbs** [comment]
Hi there,

For now, the best I can suggest is to compare the dates in your tests as strings, after converting them with `Date.toIsoString`. This will still be a valid comparison and will now give you readable output.

The internal representation looks like `RD 736956 `, which can be exposed by `Debug.toString`. The language doesn't provide a way to let types specify a custom to-string function to be used with `Debug.toString`.

Hope this helps,

Justin

**Comment by j-maas** [comment]
Ok, that's what I feared. Thanks for the quick response!
