### ISSUE TITLE
How can I express my gratitude?

### ISSUE THREAD

**Issue by lenards** [justinmimbs/elm-date-basic#12]
Justin, 

The drop-in modules you're built have been remarkably helpful and beneficial to me in getting upgraded from 0.18 to 0.19. 

Is there a way to get you a coffee ☕️  or a beer 🍺 or a book 📚 as a means of expressing my gratitude for your effort? 

Thanks 🙇 

Andrew

**Comment by justinmimbs** [comment]
Haha! Thanks, Andrew; I appreciate your kind words! I'm very glad this package has been helpful.

Thank you for putting a smile on my face. 😄

Justin

**Comment by lenards** [comment]
🙇
