### ISSUE TITLE
Minimum selectable date

### ISSUE THREAD

**Issue by mbernerslee** [justinmimbs/elm-date-basic#13]
It'd be nice to have a minimum selectable date.
I quite commonly need a datepicker that doesn't allow you to select a date in the past.

Forgive me if this is actually possible currently, but from reading the docs it seems like you can't do this.

cheers

**Comment by justinmimbs** [comment]
Hi there!

If you're looking for a minimum date of "today" for excluding past dates, then you can use the [`today`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#today) task to get the current date. Here's an [example](https://github.com/justinmimbs/date/blob/3.1.2/examples/Calendar.elm#L32) using it.

If the minimum date should be six months ago or two years ago, or something like that, then the [`add`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#add) function can help.

And if you need to ensure a date is within a range, then the [`clamp`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#clamp) and [`isBetween`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#isBetween) functions can help.

There isn't a _practical_ minimum date that the `Date` type can represent; it can represent dates at least 5 million years into the past and future.

Does this help? Please let me know if I misunderstood.

Thanks,

Justin

**Comment by justinmimbs** [comment]
I'm going to close this, but if you have any questions, please don't hesitate to ask!

Justin
