### ISSUE TITLE
min max for dates

### ISSUE THREAD

**Issue by 2mol** [justinmimbs/elm-date-basic#14]
Hi! I noticed there are not yet any min/max functions like for comparables in `core` of the type

```
min : Date -> Date -> Date
```

Are you interested in having those? I can dedicate some time and send you a PR

**Comment by justinmimbs** [comment]
Hi there!

Yes, thanks, those would be convenient helpers to include. If you're keen to, you are welcome to make a PR. (But if not, then I can probably add them within the next few days.)

Thanks,

Justin

**Comment by 2mol** [comment]
Super, I will create them, make a draft PR and then we can tweak documentation, tests etc.

Edit: here we go: https://github.com/justinmimbs/date/pull/15

**Comment by justinmimbs** [comment]
These are published in [3.2.0](https://package.elm-lang.org/packages/justinmimbs/date/3.2.0/Date#min) now; thanks for your help!
