### ISSUE TITLE
Expose default language

### ISSUE THREAD

**Issue by etaque** [justinmimbs/elm-date-basic#16]
Hello, and thanks for this great lib!

Would it be possible to expose `language_en` in next version? We'd like to reuse parts of it in various places of our application, would be great to avoid duplicating code.

Have a nice day.

**Comment by justinmimbs** [comment]
Hi Emilien,

Thanks! Have you seen the [miniBill/date-format-languages](https://package.elm-lang.org/packages/miniBill/date-format-languages/latest/DateFormat-Languages) package? It exposes several languages, including English, that can be [converted](https://package.elm-lang.org/packages/miniBill/date-format-languages/latest/DateFormat-Languages#toDateLanguage) to this library's `Language` type.

Would that work for your use case?

Justin

**Comment by etaque** [comment]
Ah, interesting, wasn't aware of this. Yes, that would solve the thing.
