### ISSUE TITLE
Formatting 2019-12-30 to "MM/dd/YYYY" returns "12/30/2020"

### ISSUE THREAD

**Issue by hpate-omicron** [justinmimbs/elm-date-basic#19]
Ellie I was using to test it: https://ellie-app.com/7H8HVcpBZ7Ma1

I create `2019-12-30` using the rata die function, `Date.fromRataDie 737423`

If I format it using the `toIsoString` function it returns the correct result:

```
Date.toIsoString december30th
-- Returns "2019-12-30"
```

But if I try to format it the year changes

```
Date.format "MM/dd/YYYY" december30th
-- Returns "12/30/2020"
```

**Comment by hpate-omicron** [comment]
Sorry, looks like I was using it incorrectly, it should be

```
Date.format "MM/dd/yyyy" december30th
-- Returns "12/30/2019"
```

If anyone else runs into this, hopefully it helps!

**Comment by justinmimbs** [comment]
Thanks, Henry. In fact, the issue before this one ran into the same confusion between the `yyyy` and `YYYY` format patterns too. I've considered adding a less-ambiguous, more-verbose version of `format` that takes a list of tokens instead of a string as a format pattern.
