### ISSUE TITLE
Closing gap to 0.18 elm-date-extra

### ISSUE THREAD

**Issue by JDemler** [justinmimbs/elm-date-basic#2]
If I understand it correctly this package is a mix between the old `elm-core/date` and `justinmimbs/elm-date-extra`.

Alas there is still some stuff from the `elm-date-extra` package missing.
I.e. `isBetween` or some way to order dates (in 0.18 I used `Date.toTime`)

Are you planning on closing that gap, or is the currently released API likely gonna stay?

**Comment by justinmimbs** [comment]
Hi Jakob,

The old `Date` from core represented a date and time of day with an implicit local offset. The `Date` in this package only represents a date. So if a date representation is all you need, then this package should work for you. I didn't include an `isBetween` function, but you can use `Date.toRataDie` to get a unique comparable (the same way you used to use `Date.toTime`).

Does this help?

Thanks,

Justin

**Comment by JDemler** [comment]
Hey Justin,

this should cover all my use-cases.

Thanks!

**Comment by justinmimbs** [comment]
Right on! 👍
