### ISSUE TITLE
Missing function toPosix

### ISSUE THREAD

**Issue by gabriela-sartori** [justinmimbs/elm-date-basic#24]
I would like to receive a date and transform it to Posix, is that possible at the moment?

**Comment by justinmimbs** [comment]
Hi Gabriel,

Sure, it's possible with the [`Time.Extra.partsToPosix`](https://package.elm-lang.org/packages/justinmimbs/time-extra/latest/Time-Extra#partsToPosix) function; you just need to specify the time and time zone you want for your `Posix` time.

Here's an example that uses midnight at UTC for the conversion.

```elm
dateToPosix : Date -> Posix
dateToPosix date =
    Time.Extra.partsToPosix Time.utc
        { year = Date.year date
        , month = Date.month date
        , day = Date.day date
        , hour = 0
        , minute = 0
        , second = 0
        , millisecond = 0
        }
```

[(Ellie)](https://ellie-app.com/bNHmH8j2s2na1)

Thanks,

Justin
