### ISSUE TITLE
Date formatting in 2019

### ISSUE THREAD

**Issue by ghost** [justinmimbs/elm-date-basic#25]
Hello,

working with 3.2.1, I got a strange formatting for the end of last year :
```
  > import Date
  > Date.fromIsoString "2019-12-31" |> Result.map (Date.toIsoString)
  Ok "2019-12-31"
  >  Date.fromIsoString "2019-12-31" |> Result.map (Date.format "dd/MM/YYYY")
  Ok "31/12/2020"
```
I did not have time to investigate code further but I report in case you have an idea.

**Comment by justinmimbs** [comment]
Hi there,

The `"YYYY"` specifies the [ISO week-numbering year](https://en.wikipedia.org/wiki/ISO_week_date), which is usually different than the calendar year around the first and last weeks of the year. You'll want to use `"yyyy"` to specify the calendar year in this case.

Hope that helps!

Justin

**Comment by ghost** [comment]
Thank you for your fast reply. Fix is perfect,  I have used `strftime` for too long. Wishing you a Merry Christmas.

**Comment by justinmimbs** [comment]
You're welcome! And thank you; wishing you a good one too. 😄

**Comment by maxfarseer** [comment]
Hi @justinmimbs , thank you for you great work!
I've just pitfall in the same issue, with `YYYY`, maybe we can find better notification for users? Or just add to readme? with `yyyy` format works as epxected, I don't know why I typed `YYYY`...
