### ISSUE TITLE
Invalid result when subtracting months

### ISSUE THREAD

**Issue by adrian-gomez** [justinmimbs/elm-date-basic#28]
Hey I have found an issue when using  https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#add`, here is a simple reproduction script:
```
        may2021 =
            Result.toMaybe (Date.fromIsoString "2021-05-01")

        dec2020 =
            Maybe.map (Date.add Date.Months -5) may2021

        jan2021 =
            Maybe.map (Date.add Date.Months -4) may2021

        feb2021 =
            Maybe.map (Date.add Date.Months -3) may2021

        _ =
            Debug.log "may2021" (Maybe.map (Date.format "dd-MM-YYYY") may2021)

        _ =
            Debug.log "dec2020" (Maybe.map (Date.format "dd-MM-YYYY") dec2020)

        _ =
            Debug.log "jan2021" (Maybe.map (Date.format "dd-MM-YYYY") jan2021)

        _ =
            Debug.log "feb2021" (Maybe.map (Date.format "dd-MM-YYYY") feb2021)
```
it will print out:
```
may2021: Just "01-05-2021"
dec2020: Just "01-12-2020"
jan2021: Just "01-01-2020"
feb2021: Just "01-02-2021"
```
Notice how `jan2021` is  `"01-01-2020"` instead of `"01-01-2021"`.

I'll try to use a workaround of adding positive numbers instead of negatives, but it would be nice if I could keep my logic as is.

**Comment by justinmimbs** [comment]
Hi Adrian,

The `YYYY` formatting pattern indicates the ISO week-numbering year; if you change it to `yyyy`, for the calendar year, then you should see the date you expect. There's more info on date formatting patterns [here](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#format).

Hope this helps!

Thanks,

Justin

**Comment by adrian-gomez** [comment]
@justinmimbs thanks for the reply! I tried your suggestion but I got:
```
may2021: Just "01-05-2021"
dec2020: Just "01-12-2020"
jan2021: Just "01-01-2021"
feb2021: Just "01-02-2021"
```
I don't think it's a problem when formatting the date.

I'm pretty sure the problem is in this line:
```
jan2021 = Maybe.map (Date.add Date.Months -4) may2021
```

**Comment by adrian-gomez** [comment]
Hi Justin, tanks for quick reply! It worked, we where using `Y` and its variations a bunch I have changed all of them to be `y` and everything seems to work now.

Thanks!!!

**Comment by justinmimbs** [comment]
You're welcome! Glad to hear it. 👍🏼
