### ISSUE TITLE
fromIsoString should return why detailed reason why the date is invalid

### ISSUE THREAD

**Issue by psilospore** [justinmimbs/elm-date-basic#31]
In the example:
```
fromIsoString "2018-02-29"
    == Err "Invalid calendar date (2018, 2, 29)"
```
I would like to have more detailed messages. For example, I might expect it to mention that the day field is invalid and a valid range for the day field (01 to 28). I would expect the same for the month field (01 to 12).

**Comment by justinmimbs** [comment]
Hi there,

That sounds good. I'll try to make this change soon. It fits in well with #26, which requests strict constructors, so it would be nice to expose the strict constructors with improved error messages.

Thanks,

Justin

**Comment by justinmimbs** [comment]
I just published [4.0.1](https://package.elm-lang.org/packages/justinmimbs/date/4.0.1/) with more detailed error messages. Your example now gives:

```elm
Date.fromIsoString "2018-02-29"
    == Err "Invalid date: day 29 is out of range (1 to 28) for February (2018 is not a leap year); received (year 2018, month 2, day 29)"
```

I hope that helps.

Justin

**Comment by psilospore** [comment]
Thanks! This is great!

**Comment by justinmimbs** [comment]
Sure thing--thanks for the report!
