### ISSUE TITLE
Expose `withOrdinalSuffix`

### ISSUE THREAD

**Issue by kutyel** [justinmimbs/elm-date-basic#32]
Hi! Thanks for this lib, we are using it heavily and it always spares me a lot of stuff working with `Date` 🙌🏻 

If we had `withOrdinalSuffix` exposed, we could get rid of some code and people would not have to use https://package.elm-lang.org/packages/lynn/elm-ordinal/1.0.4/Ordinal for example 😉 

I can propose the PR doing so if you agree!

**Comment by justinmimbs** [comment]
Hi Flavio! I'm sorry for the delayed reply. Thank you for the kind words--I'm glad this library is helping out. 😀 If that function would help, then let's expose it; I would gladly take a PR to do so. Thank you!
