### ISSUE TITLE
Error when trying to parse an actually ISO8601 valid date string

### ISSUE THREAD

**Issue by n1k0** [justinmimbs/elm-date-basic#7]
Using latest 3.1.1, trying to parse this ISO 8601 formatted date `2018-07-30T09:58:48.841Z`, I'm getting an error saying it's invalid:

```
> import Date
> Date.fromIsoString "2018-07-30T09:58:48.841Z"
Err ("String is not in IS0 8601 date format")
    : Result String Date.Date
```

**Comment by justinmimbs** [comment]
Hi Nicolas,

You're right, that error message is misleading. `fromIsoString` is meant to parse only ISO 8601 _dates_, not dates with times. I will make the error message better!

If you just want the _UTC_ date from this UTC time string, then you can simply truncate the time part:

```elm
import Date

Date.fromIsoString (String.left 10 "2018-07-30T09:58:48.841Z")
    == Ok (RD 736905)
```

But if you want the _local_ date from this UTC time string, then you can use, for example,`rtfeldman/elm-iso8601-date-strings` to parse it to `Posix`, and then convert with `Date.fromPosix` and a time zone.

```elm
import Date
import Iso8601
import Time

Iso8601.toTime "2018-07-30T09:58:48.841Z"
    |> Result.map (Date.fromPosix Time.utc)
    == Ok (RD 736905)
```

Hope this helps.

Thanks,

Justin

**Comment by n1k0** [comment]
That makes a lot of sense, thanks. Indeed, I feel like the error message could be slightly improved :)

Thanks for your work, cheers!

**Comment by n1k0** [comment]
Just a last thought; would it make sense to parse ISO 8601 datetimes to extract only the date part of it?

**Comment by justinmimbs** [comment]
Good question! While that sounds convenient, I think implicitly throwing away information could end up hiding problems. I would rather require users to express their intent explicitly.

For example, these two strings represent the same moment in time, and both will parse to the same `Posix`.

`2018-07-30T09:58:48.841Z`
`2018-07-29T23:58:48.841-10:00`

The date in UTC is not the same as the date in Honolulu at this time, and, given either string, I don't know which date the user really wants. :)

**Comment by n1k0** [comment]
Well I'd expect to have the returned date to match the TZ specified in the datetime, eg. `2018-07-30` in the first case and `2018-07-29` in the second example.

Alternatively we could attach a tz to the date type, or create a `ZonedDate` one, but frankly that sounds horribly overkill for now so... I think we can live with the current implementation :+1:

**Comment by justinmimbs** [comment]
I updated the error messages in [3.1.2](https://package.elm-lang.org/packages/justinmimbs/date/3.1.2/), so hopefully they're more clear. Your original example now gives the following:

```elm
import Date

Date.fromIsoString "2018-07-30T09:58:48.841Z"
    == Err "Expected a date only, not a date and time"
```

Thanks for the report!
