### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by sporto** [justinmimbs/elm-date-basic#8]
Hi
Thanks for making this package, is very nice.

Could you please add a changelog to the repo? It is very useful for upgrading, specially when functions are removed or renamed.

Thanks

**Comment by justinmimbs** [comment]
Hi Sebastian,

Certainly! [CHANGELOG](https://github.com/justinmimbs/date/blob/master/CHANGELOG.md)

Out of curiosity, were you using any of the removed functions or the removed module?

Thanks,

Justin

**Comment by sporto** [comment]
Thanks.
No, we were not using the removed module.
