### ISSUE TITLE
To unix timestamp

### ISSUE THREAD

**Issue by lionar** [justinmimbs/elm-date-basic#9]
Hi Justin,

Sorry to have to ask you this but is there a way to convert a *type Date* back to *unix timestamp*.

Aron

**Comment by justinmimbs** [comment]
Hi Aron,

No worries! Yes, you can use the `partsToPosix` function in [justinmimbs/time-extra](https://package.elm-lang.org/packages/justinmimbs/time-extra/latest/) to convert the parts of a `Date` to a UNIX time (as a `Posix`) in any time zone.

```elm
import Date exposing (Date)
import Time exposing (Posix, Zone)
import Time.Extra as Time

dateToPosix : Zone -> Date -> Posix
dateToPosix zone date =
    Time.Parts (Date.year date) (Date.month date) (Date.day date) 0 0 0 0
        |> Time.partsToPosix zone
```

Justin

**Comment by lionar** [comment]
Hey Justin,

That did it for me. Thanks a lot!

Aron
